# .github/workflows/manual_scraper_trigger.yml
name: Manually Trigger Fly Scraper VM

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    steps:
      # Install Fly.io CLI
      - uses: superfly/flyctl-actions/setup-flyctl@v1

      # Quick sanity-check: secret present?
      - name: Verify token is present
        run: echo "Has token? ${{ secrets.FLY_API_TOKEN != '' }}"

      # Set environment variable to use ManualAncSpider and start the machine
      - name: Run manual scraper and wait for completion
        run: |
          # Update machine with environment variable to use ManualAncSpider
          flyctl --access-token "$FLY_API_TOKEN" \
                 machine update e2867d5f615e38 --app flyscraper \
                 --env SPIDER_NAME=ManualAncSpider --skip-start

          # Start the machine
          flyctl --access-token "$FLY_API_TOKEN" \
                 machine start e2867d5f615e38 --app flyscraper

          # Poll every 30 s, up to 15 minutes (30 × 30 s)
          for i in {1..30}; do
            # Capture the current state (parse the plain-text output)
            status=$(flyctl --access-token "$FLY_API_TOKEN" \
                     machine status e2867d5f615e38 --app flyscraper \
                     | awk '/State:/ {print tolower($2)}')
            echo "Machine status: $status"

            if [ "$status" = "stopped" ]; then
              echo "Machine completed successfully"
              
              # Reset environment variable back to default (AncSpider) for nightly runs
              flyctl --access-token "$FLY_API_TOKEN" \
                     machine update e2867d5f615e38 --app flyscraper \
                     --env SPIDER_NAME=AncSpider --skip-start
              
              exit 0
            fi

            sleep 30
          done

          echo "Timeout: Machine did not complete within 15 minutes"
          
          # Reset environment variable back to default even on timeout
          flyctl --access-token "$FLY_API_TOKEN" \
                 machine update e2867d5f615e38 --app flyscraper \
                 --env SPIDER_NAME=AncSpider --skip-start
          
          exit 1 